# CarParts-Seg Dataset Config (YOLOv8 segment)
# Bu yaml dosyası: src/yolo/configs/carparts-seg.yaml

# Dataset kök klasörü (yaml'e göre relative)
# -> src/yolo/configs/../../autodamageid/data/carparts_seg
path: ../../autodamageid/data/carparts_seg

train: images/train
val: images/val
test: images/test

names:
  0: back_bumper
  1: back_door
  2: back_glass
  3: back_left_door
  4: back_left_light
  5: back_light
  6: back_right_door
  7: back_right_light
  8: front_bumper
  9: front_door
  10: front_glass
  11: front_left_door
  12: front_left_light
  13: front_light
  14: front_right_door
  15: front_right_light
  16: hood
  17: left_mirror
  18: object
  19: right_mirror
  20: tailgate
  21: trunk
  22: wheel
